<?php

namespace MIKA\BasecodeBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function countArticlesBySc($nom)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.sousCategorie = :nom')
            ->setParameter('nom',$nom)
            ->select('COUNT(a)');

        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}