<?php

namespace MIKA\BasecodeBundle\Repository;

/**
 * SousCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function choix($categorie){
        return $this->createQueryBuilder('p')
            ->where('p.categorie = :categorie')
            ->setParameter(':categorie', $categorie);

    }

    public function countArticlesByC($nom)
    {
        $qb = $this->createQueryBuilder('sc')
            ->where('sc.categorie = :nom')
            ->setParameter('nom',$nom)
            ->select('COUNT(sc)');

        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}
